default:
  golem_name: rph2023.breakapp
  golem_version: 0.0.0.9002
  app_prod: no
  quiz_time: 60
  penalty_time: 5
  db_type: LOCAL
  allow_multiple_attempts: TRUE

production:
  app_prod: yes
  quiz_time: 1200
  penalty_time: 30
  db_type: SERVER

dev:
  golem_wd: !expr golem::pkg_path()

