default:
  golem_name: rph2023.breakapp
  golem_version: 0.0.0.9002
  app_prod: no
  quiz_time: 60
  penalty_time: 0
  db_type: LOCAL
  allow_multiple_attempts: yes

production:
  app_prod: yes
  quiz_time: 1200
  penalty_time: 60
  db_type: SERVER
  allow_multiple_attempts: no

production-load-test:
  app_prod: yes
  quiz_time: 1200
  penalty_time: 60
  db_type: SERVER
  allow_multiple_attempts: yes

dev:
  golem_wd: !expr golem::pkg_path()

