# fly.toml app configuration file generated for rph2023breakapp on 2023-10-16T00:15:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rph2023breakapp"
primary_region = "bos"

[build]
  image = "rpodcast/rph2023.breakapp"

[http_service]
  internal_port = 2550
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
